name: GuitarTuner
options:
  bundleIdPrefix: com.guitartuner.ios
  deploymentTarget:
    iOS: 16.0
packages:
  AudioKit:
    url: https://github.com/AudioKit/AudioKit.git
    from: 5.6.2
  AudioKitEX:
    url: https://github.com/AudioKit/AudioKitEX.git
    from: 5.6.0
  SoundpipeAudioKit:
    url: https://github.com/AudioKit/SoundpipeAudioKit.git
    from: 5.6.0
targets:
  GuitarTuneriOS:
    type: application
    platform: iOS
    sources:
      - path: Source
    dependencies:
      - package: AudioKit
      - package: AudioKitEX
      - package: SoundpipeAudioKit
    settings:
      base:
        INFOPLIST_FILE: Source/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.guitartuner.ios
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
